import ReduxProvider from "@/components/redux/ReduxProvider";
import AdminSidebar from "./AdminSidebar";
import Navbar from "@/components/navbar/Navbar";
import AdminHeader from "./AdminHeader";
import AdminSidebarWrapper from "./AdminSidebarWrapper";

export const metadata = {
    title: "MAGDESIGN ADMIN",
    description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
    return (
      <html lang="en">
        <body>
          <div className="w-full">
            <ReduxProvider>
              <div className="w-full flex items-start ">
                <div className="w-3/12">
                  <AdminSidebarWrapper />
                </div>
                <div className="flex flex-col w-full">
                  <div className="w-full">
                    <AdminHeader />
                  </div>
                  <div className="w-full">
                    {children}
                  </div>
                </div>
              </div>
            </ReduxProvider>
          </div>
        </body>
      </html>
    );
  }
  